### ISSUE TITLE
[Misc] プルリク テンプレート 議論

### ISSUE THREAD

**Issue by ywake** [kohkubo/minishell#149]
## 目的
プルリクの負担を減らそう！
* プルリクのの負担とは
  * 作るときの負担
  * みるときの負担

プルリクが作りづらい・分かりづらいのはテンプレートの責任

僕が修正案をコメントするのでフィードバックをください。

**Comment by ywake** [comment]
[Reviewerに優しいPull Requestの作り方](https://qiita.com/sakusrai/items/967cb9c784f1b72aba07)

**Comment by ywake** [comment]
# 改善案
## 概要

* このプルリクの概要
* 設計・参照
* 関連するIssueやプルリクエスト

## 詳細
（テストコードは含みません）

| 追加した関数 | 処理の流れ |
:-|:-
| | |

| 変更した関数 | 変更内容とその理由 |
:-|:-
| | |

## やらないこと（あれば）
〜〜〜略〜〜〜

**Comment by ywake** [comment]
@kohkubo これどうですか？

**Comment by kohkubo** [comment]
追加、変更以外にもいろいろあると思うので

やった処理(変更箇所): 詳細 
のフォーマットで以下のような感じではどうでしょうか

edit(parse.c/parse): 何を変更したか
add(parse.c/is_parse): どういう関数を追加したか
move(parse.c/parse => main.c/parse): なぜ移動したか
refactor(env.c/store_shellenv): 何をリファクタリングしたか
fix(parse.c/parse): どういったバグをどうやって修正したか

**Comment by ywake** [comment]
fix, edit, refactorは同じじゃないですか？

**Comment by kohkubo** [comment]
refactor 機能の変更を伴わない変更
fix バグの修正
edit 既存の機能の変更
です。

**Comment by ywake** [comment]
書く内容は同じじゃないですか？

**Comment by ywake** [comment]
| 変更した関数 | 変更内容とその理由 |
:-|:-
`parse.c/parse()` | 〇〇はXXXなので、△△へ変更
`env.c/store_shellenv()` | リファクタリング

**Comment by kohkubo** [comment]
テーブルの形式合わせるならこうなります。

変更内容 | 変更した関数 | 変更内容とその理由
-- | -- | --
edit | parse.c/parse() | 〇〇はXXXなので、△△へ変更
fix | parse.c/parse() | 〇〇でXXXなバグがあったので、△△に修正
refactor  | env.c/store_shellenv() | 不要な分岐を消去

こっちのほうが読みやすくないですか

**Comment by ywake** [comment]
タグのような項目を付けるのはいいですが、現状説明が概要レベルにとどまっているのでそこを改善したいんですよね

**Comment by kohkubo** [comment]
修正しました。こんな感じですかね

**Comment by kohkubo** [comment]
こうすれば強制的に書かせることはできますね

変更内容 | 変更した関数 | 変更内容 | その理由
-- | -- | --
edit | parse.c/parse() | 〇〇を、△△へ変更 | 課題PDFの変更に伴い 
fix | parse.c/parse() | XXを、△△に修正 | 不要な分岐があったため
refactor | env.c/store_shellenv() | 不要な分岐を消去 | 不要な分岐

**Comment by ywake** [comment]
そうですね
説明をより細かくしたいのでテンプレに説明項目を増やします。リファクタは別にします

変更した関数 | 問題 | 変更
-|-|-
parse.c/parse() | XX | 〇〇を、△△へ変更
parse.c/parse() | XX | △△に修正

**Comment by kohkubo** [comment]
プルリクがイシュー単位で細かい前提なので、テーブルである必要性をあまり感じないのですが、とりあえずやってみてそれで手間だったら、コミットコメントを流用できる形を提案したいと思います。

**Comment by ywake** [comment]
同じくリファクタリングやバグフィックスが混ざっている状況はあまりよろしくないかと思います。

**Comment by kohkubo** [comment]
ですね。基本は異なる種類の変更は混ざらない前提です。

**Comment by ywake** [comment]
ただプルリクのコメントはissueの説明ではないのでコードの説明をしてもらう必要があります

**Comment by kohkubo** [comment]
僕はwakeさんの現状の案で大丈夫です(*ﾟ∀ﾟ)

**Comment by kohkubo** [comment]
関数コメントとの棲み分けも考えたいですね

**Comment by ywake** [comment]
関数内にコメントするのが禁止されているため、コメントで表すのはその関数がなにをできるか・使い方になると思います
