### ISSUE TITLE
[expand] シングルクォートの展開

### ISSUE THREAD

**Issue by kohkubo** [kohkubo/minishell#186]

**Comment by kohkubo** [comment]
双方向リストがあったほうが実装しやすいので、push_swapで作成したライブラリにテストを追加した後、取り組みます。

**Comment by ywake** [comment]
ちなみにどんな実装で双方向必要になりそうですか？
双方向リストは便利ですけどlibftでせっかく作った関数たちが再実装・再テストになるのが手間なんですよね
push_swapも僕がやった感じだと双方向で楽になるのは1箇所程度で、それも単方向が辛いかといえば全然辛くもならなかったんですよね

**Comment by kohkubo** [comment]
以下のケースで必要かと思いましたが、不要でした！単方向リストのまま行きます！

```
echo '$USER $USER'
```
